# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql2
  database: gw_development
  host: 127.0.0.1
  user: root
  password: pass
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: gw_test
  host: 127.0.0.1
  user: root
  password: pass
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: gw_production
  host: 127.0.0.1
  user: root
  password: pass
  pool: 5
  timeout: 5000
