# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
adapter: mysql2
encoding: utf8
reconnect: false
database: gw_development
pool: 5
username: root
password: pass
host: localhost
port: 3306

test:
adapter: mysql2
encoding: utf8
reconnect: false
database: gw_test
pool: 5
username: root
password: pass
host: localhost
port: 3306

production:
adapter: mysql2
encoding: utf8
reconnect: false
database: gw_production
pool: 5
username: root
password: pass
host: localhost
port: 3306
