# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gw_deveĺopment
  pool: 5
  username: root
  password: pass
  shost: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gw_test
  pool: 5
  username: root
  password: pass
  shost: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gw_production
  pool: 5
  username: root
  password: pass
  shost: localhost

